digapp:
  image: digmemex/digapp:1.0.5
  ports:
    - "8080:8080"
  links:
    - mysql
  volumes:
    - ./logs/digapp:/var/log
  environment:
    EUI_SERVER_URL: 'http://digappdev.dig.isi.edu'
    EUI_SERVER_PORT: '80'
    IMAGE_SIM_URL: 'http://digappdev.dig.isi.edu'
    IMAGE_SIM_PORT: '80'
    EUI_SEARCH_INDEX: 'dig-latest'
    BLUR_IMAGES: 'false'
    DB_HOST: 'mysql'
    DB_PORT: 3306
    DB_USER: 'digapp'
    DB_PASS: secret
    NODE_ENV: 'production'

notifyapp:
  image: digmemex/notifyapp:1.0.0
  links:
    - mysql
  volumes: 
    - ./logs/notifyapp:/var/log
  environment:
    NODE_ENV: 'production'
    DB_USER: 'digapp'
    DB_PASS: secret
    DB_HOST: 'mysql'
    DB_PORT: 3306
    ES_USER: 'memex'
    ES_PASS: secret
    EUI_SERVER: 'digappdev.dig.isi.edu'
    EUI_SERVER_PORT: 80
    EUI_SEARCH_INDEX: 'dig-latest'
    EUI_SEARCH_TYPE: 'WebPage'

mysql:
  image: mysql
  volumes_from:
    - mysqldata
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: 'digapp_production'
    MYSQL_USER: 'digapp'
    MYSQL_PASSWORD: secret

mysqldata:
  image: busybox
  volumes: 
    - /var/lib/mysql

nginx:
  image: nginx
  links:
    - digapp
  ports:
    - "80:80"
  volumes:
    - ./conf/nginx/.htpasswd:/etc/nginx/.htpasswd
    - ./conf/nginx_sites_enabled/dig:/etc/nginx/conf.d/default.conf
    - ./logs/nginx:/var/log/nginx

mongo:
  image: mongo
  volumes_from:
    - mongodata

mongodata:
  image: busybox
  volumes:
    - /data/db/
